
   EMail: ve7jtb@ve7jtb.com
   URI:   http://www.thread-safe.com/engines:
  golint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - go

ratings:
  paths:
    - "**.go"
